In [1]:
from scipy import signal
from scipy import misc

%matplotlib inline
%matplotlib notebook
%pylab

import numpy as np
import matplotlib.pyplot as plt 
import matplotlib.patches as patches
from mpl_toolkits.mplot3d import axes3d
from challenge.starGen import *
from solver.solver import *
from common import *

from scipy.spatial.transform import Rotation as R

np.random.seed(0)

Using matplotlib backend: nbAgg
Populating the interactive namespace from numpy and matplotlib


In [2]:
stars_xyzm = np.array(genStars())
print(stars_xyzm)

[[ 4.90798490e-01  7.32831676e-03  8.71242296e-01  5.49997831e+02]
 [-3.84388060e-02 -8.43492785e-01  5.35763362e-01  5.49867684e+02]
 [-6.48160348e-01  7.11248384e-01 -2.72054958e-01  5.49785384e+02]
 ...
 [ 4.79666097e-01 -4.11877094e-01  7.74775900e-01  5.02011920e+01]
 [ 6.84566415e-01 -1.45708036e-02  7.28804854e-01  5.01122039e+01]
 [ 2.06728749e-02  3.18273686e-01 -9.47773440e-01  5.00490964e+01]]


In [3]:
# Start Generating a set of stars
viewable, viewable_idx, quat = genQuestion(stars_xyzm)
print(quat)
loss = 0
A = R.from_quat(quat).as_dcm()
for ii in range(len(viewable)):
    x,y = viewable[ii,:3], stars_xyzm[viewable_idx[ii],:3]
    loss += np.linalg.norm(A @ y - x) * (1.0/len(viewable))
print(loss)

#while True:
#    quat = normalizeV(np.random.rand(4))
#    if (quat[3] > 0.00001):
#        break
#target = rotateByQuat(quat, np.array([0,0,1]))
#viewable, viewable_idx = selectViewable(stars_xyzm, target)
#noise = np.random.rand(viewable.shape[0], viewable.shape[1]) * 0.0001
#viewable += noise


[0.59029825 0.05832714 0.17364454 0.78612562]
0.9931153950585626


In [4]:
X = np.array(stars_xyzm[viewable_idx,:3])
Y = np.array(viewable[:,:3])

B = makeB(X,Y)
A = makeA(B)
print(A)

[[ 0.93267414 -0.20473887  0.29698644]
 [ 0.34238877  0.24334727 -0.90749768]
 [ 0.11352921  0.94808444  0.29706399]]


In [9]:
#guess = solve(X,Y)
#A = R.from_quat(guess).as_dcm()
print(A)
loss = 0
for ii in range(len(viewable)):
    x,y = viewable[ii,:3], stars_xyzm[viewable_idx[ii],:3]
    loss += np.linalg.norm(A @ y - x) * (1.0/len(viewable))
print(loss)

[[ 0.93267414  0.34238877  0.11352921]
 [-0.20473887  0.24334727  0.94808444]
 [ 0.29698644 -0.90749768  0.29706399]]
1.0051323909369925


In [10]:
quat = R.from_quat(quat).inv().as_quat()
print(quat)

print(guess)
print(np.abs(np.dot(guess,quat)))

[ 0.59029825  0.05832714  0.17364454 -0.78612562]
[-0.58997095 -0.0583291  -0.17395587  0.78630233]
0.9999998823564429
